import { Assistant} from "next/font/google";
import "./globals.css";

const assistnatFont = Assistant(
  {
    weight : ['200','400','600','700','800'],
    subsets:['latin'],
    display:'swap'
  }
)
export const metadata = {
  title: "Surya site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={ `${assistnatFont.className}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
